import "./globals.css";
import LayoutSelector from "./Components/LayoutSelector";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
       <LayoutSelector>{children}</LayoutSelector> 
      </body>
    </html>
  );
}
